language: ruby
sudo: false
cache:
  - bundler

rvm:
  - 2.1
  - 2.2

deploy:
  provider: rubygems
  api_key:
    secure: LcWSsGG1GhvdlDz0A9x02EcszoaS3bT7666XlN0s2bH713AWHNMIdK0GKQivpHdDFOzg6bj/UwSikWGaF/F01B8pnEmVxQoMLqudrjBIbnMpkZVcXNarP3oLOuPI+QdF6VEX4v9mrtjUd1nTTitMGn3DDk3gDhRRYbPIg5/UhkA=
  gem: say_it_with_graphs
  on:
    repo: nesQuick/say-it-with-graphs
